name: class_2021_03
channels:
  - defaults
  - conda-forge
  - nsls2forge
  - aps-anl-tag
dependencies:
  # - anaconda
  - area-detector-handlers
  - bluesky>=1.6.2
  - databroker-pack
  - databroker>=1.2
  - h5py
  - imagecodecs-lite
  - ipympl
  - ipython
  - jupyter
  - jupyterlab
  - lxml
  - notebook
  - ophyd>=1.5.1
  - pint
  - pip
  - psutil
  - pyEpics>=3.4.2
  - pylint
  - pymongo
  - pyqt=5
  - pyRestTable
  - python>=3.8
  - qt=5
  - scikit-image
  - spec2nexus
  - stdlogpj
  - versioneer
  - xlrd
  - aps-dm-api
  - apstools
  - black
  - flake8
  - hklpy
  - nexpy
  - pandas
  - punx
  - pymca
  - sphinx
  - sphinxcontrib-napoleon
  - pytest
  - pip:
    - bluesky-live
    # - sphinx-rtd-theme
    - super-state-machine
